# Generated by Django 4.2.28 on 2026-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='card_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
