# Generated by Django 4.2.28 on 2026-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deckcard_card_type_deckcard_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='atk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='attribute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
