# Generated by Django 4.2.28 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deckcard_atk_deckcard_attribute_deckcard_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='custom_tags',
            field=models.TextField(default='[]'),
        ),
    ]
