# Generated by Django 4.2.28 on 2026-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deckcard_custom_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='raw_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='raw_main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='raw_side',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='section',
            field=models.CharField(default='main', max_length=20),
        ),
    ]
