# Generated by Django 4.2.28 on 2026-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deck_raw_extra_deck_raw_main_deck_raw_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='raw_extra',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='raw_main',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='raw_side',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='section',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='area',
            field=models.CharField(default='MAIN', max_length=10),
        ),
    ]
